steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=Dockerfile'
      - '--context=.'
      - '--destination=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend:latest'
      - '--cache=true'
      - '--cache-ttl=24h'
      - '--cache-repo=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend-cache'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mvp-backend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend:latest'
      - '--region'
      - 'europe-west1'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend:latest'