steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend:latest'
    allowFailure: true

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend:latest'
      - '--tag'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mvp-backend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend:latest'
      - '--region'
      - 'europe-west1'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mvp-backend:latest'