"""Pydantic schemas for AI-powered enrichment/SEO endpoints."""
from typing import Dict, List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field


AIEnrichmentTargetField = Literal["title", "description", "meta_description"]


class AITextOptimizationRequest(BaseModel):
    """Optimize free text using AI and optional SEO keywords."""

    content: str = Field(..., min_length=5, description="Original text content to optimize")
    keywords: List[str] = Field(
        default_factory=list,
        description="Keywords for SEO guidance (first keyword is treated as primary)",
    )
    fields: List[AIEnrichmentTargetField] = Field(
        default_factory=lambda: ["title", "description", "meta_description"],
        description="Which output fields should be generated by AI",
    )


class AIListingEnrichmentRequest(BaseModel):
    """AI enrichment request for an existing listing."""

    listing_id: UUID
    fields: List[AIEnrichmentTargetField] = Field(
        default_factory=list,
        description="Listing fields to enrich with AI",
    )
    keywords: List[str] = Field(
        default_factory=list,
        description="Optional custom keywords. If empty, keywords are inferred from listing.",
    )
    apply: bool = Field(
        False,
        description="Persist AI results to DB when true; otherwise preview only",
    )
    force: bool = Field(
        False,
        description="Regenerate even when target fields already have values",
    )


class AIEnrichmentOutput(BaseModel):
    """AI generated SEO output."""

    title: Optional[str] = None
    description: Optional[str] = None
    meta_description: Optional[str] = None


class AIEnrichmentFieldResult(BaseModel):
    """Before/after AI enrichment result for a specific field."""

    field: AIEnrichmentTargetField
    original: Optional[str] = None
    enriched: Optional[str] = None
    changed: bool = False


class AITextOptimizationResponse(BaseModel):
    """Response for free-text AI optimization."""

    model_used: str
    keywords_used: List[str] = Field(default_factory=list)
    output: AIEnrichmentOutput


class AIListingEnrichmentResponse(BaseModel):
    """Response for listing AI enrichment."""

    listing_id: UUID
    applied: bool = False
    model_used: str
    keywords_used: List[str] = Field(default_factory=list)
    results: List[AIEnrichmentFieldResult] = Field(default_factory=list)

class EnrichmentPreview(BaseModel):
    """Preview of AI enrichment for a single listing — description only."""

    original_description: Optional[str] = None
    enriched_description: Optional[str] = None
    model_used: str


class EnrichmentSourceStats(BaseModel):
    """Enrichment counts per source partner."""

    total: int
    enriched: int


class EnrichmentStats(BaseModel):
    """Aggregated enrichment statistics."""

    total_listings: int
    enriched_count: int
    not_enriched_count: int
    enrichment_percentage: float
    by_source: Dict[str, EnrichmentSourceStats] = Field(default_factory=dict)