"""Make scrape_job_id NOT NULL and source_url NOT NULL

Revision ID: 3b97b6bb5e3e
Revises: ab83cfce0a7a
Create Date: 2026-02-25 15:58:38.526986
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b97b6bb5e3e'
down_revision: Union[str, None] = 'ab83cfce0a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_configs_key'), table_name='enrichment_configs')
    op.drop_table('enrichment_configs')
    op.alter_column('character_mappings', 'source_chars',
               existing_type=sa.VARCHAR(length=20),
               comment='Source characters to replace',
               existing_nullable=False)
    op.alter_column('character_mappings', 'target_chars',
               existing_type=sa.VARCHAR(length=20),
               comment='Replacement characters',
               existing_nullable=False)
    op.alter_column('character_mappings', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment="Category: 'mojibake', 'currency', 'symbol'",
               existing_nullable=False,
               existing_server_default=sa.text("'mojibake'::character varying"))
    op.alter_column('field_mappings', 'source_name',
               existing_type=sa.VARCHAR(length=100),
               comment="Raw field name from HTML (e.g., 'preço', 'price', 'quartos')",
               existing_nullable=False)
    op.alter_column('field_mappings', 'target_field',
               existing_type=sa.VARCHAR(length=50),
               comment="Canonical field name (e.g., 'price', 'bedrooms', 'has_garage')",
               existing_nullable=False)
    op.alter_column('field_mappings', 'mapping_type',
               existing_type=sa.VARCHAR(length=20),
               comment="Type: 'field' (data field) or 'feature' (boolean amenity)",
               existing_nullable=False,
               existing_server_default=sa.text("'field'::character varying"))
    op.alter_column('field_mappings', 'language',
               existing_type=sa.VARCHAR(length=5),
               comment="Language code: 'pt', 'en', 'es', etc.",
               existing_nullable=False,
               existing_server_default=sa.text("'pt'::character varying"))
    op.alter_column('field_mappings', 'site_key',
               existing_type=sa.VARCHAR(length=50),
               comment='Optional site key for site-specific mappings (NULL = global)',
               existing_nullable=True)
    op.alter_column('field_mappings', 'priority',
               existing_type=sa.INTEGER(),
               comment='Higher priority mappings override lower ones',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('listings', 'scrape_job_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Foreign key to scrape_jobs')
    op.alter_column('listings', 'partner_id',
               existing_type=sa.VARCHAR(length=255),
               comment='ID on the original site (e.g. REF-12345)',
               existing_nullable=True)
    op.alter_column('listings', 'source_partner',
               existing_type=sa.VARCHAR(length=50),
               comment='pearls',
               existing_nullable=False)
    op.alter_column('listings', 'source_url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False,
               comment='Original listing URL (deduplication)')
    op.alter_column('listings', 'listing_type',
               existing_type=sa.VARCHAR(length=20),
               comment='sale, rent',
               existing_nullable=True)
    op.alter_column('listings', 'property_type',
               existing_type=sa.VARCHAR(length=50),
               comment='apartment, house, land, etc.',
               existing_nullable=True)
    op.alter_column('listings', 'typology',
               existing_type=sa.VARCHAR(length=10),
               comment='T0, T1, T2, T3, etc.',
               existing_nullable=True)
    op.alter_column('listings', 'price_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Price in numeric form',
               existing_nullable=True)
    op.alter_column('listings', 'energy_certificate',
               existing_type=sa.VARCHAR(length=10),
               comment='A+, A, B, B-, C, D, E, F',
               existing_nullable=True)
    op.alter_column('listings', 'raw_description',
               existing_type=sa.TEXT(),
               comment='Original unmodified description',
               existing_nullable=True)
    op.alter_column('listings', 'description',
               existing_type=sa.TEXT(),
               comment='Cleaned description',
               existing_nullable=True)
    op.alter_column('listings', 'enriched_description',
               existing_type=sa.TEXT(),
               comment='AI-enriched description',
               existing_nullable=True)
    op.alter_column('listings', 'description_quality_score',
               existing_type=sa.INTEGER(),
               comment='0-100 quality score',
               existing_nullable=True)
    op.alter_column('listings', 'headers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Structured headers as JSON array',
               existing_nullable=True)
    op.alter_column('listings', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Complete original payload',
               existing_nullable=True)
    op.alter_column('listings', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               comment='Full-text search tsvector — managed by DB trigger',
               existing_nullable=True)
    op.drop_index(op.f('ix_listings_search_vector'), table_name='listings', postgresql_using='gin')
    op.alter_column('media_assets', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='photo, floorplan, video',
               existing_nullable=True)
    op.alter_column('media_assets', 'position',
               existing_type=sa.INTEGER(),
               comment='Display order',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'site_key',
               existing_type=sa.VARCHAR(length=50),
               comment='pearls',
               existing_nullable=False)
    op.alter_column('scrape_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, running, completed, failed, cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('scrape_jobs', 'progress',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='{"pages_visited": 0, "listings_found": 0, "listings_scraped": 0, "errors": 0}',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Runtime config: min_delay, max_delay, user_agent, etc.',
               existing_nullable=True)
    op.alter_column('site_configs', 'selectors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('site_configs', 'pagination_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(op.f('site_configs_key_key'), 'site_configs', type_='unique')
    op.drop_index(op.f('ix_site_configs_key'), table_name='site_configs')
    op.create_index(op.f('ix_site_configs_key'), 'site_configs', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_configs_key'), table_name='site_configs')
    op.create_index(op.f('ix_site_configs_key'), 'site_configs', ['key'], unique=False)
    op.create_unique_constraint(op.f('site_configs_key_key'), 'site_configs', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('site_configs', 'pagination_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('site_configs', 'selectors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('scrape_jobs', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Runtime config: min_delay, max_delay, user_agent, etc.',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'progress',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{"pages_visited": 0, "listings_found": 0, "listings_scraped": 0, "errors": 0}',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, running, completed, failed, cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('scrape_jobs', 'site_key',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pearls',
               existing_nullable=False)
    op.alter_column('media_assets', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Display order',
               existing_nullable=True)
    op.alter_column('media_assets', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='photo, floorplan, video',
               existing_nullable=True)
    op.create_index(op.f('ix_listings_search_vector'), 'listings', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('listings', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               comment=None,
               existing_comment='Full-text search tsvector — managed by DB trigger',
               existing_nullable=True)
    op.alter_column('listings', 'raw_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Complete original payload',
               existing_nullable=True)
    op.alter_column('listings', 'headers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Structured headers as JSON array',
               existing_nullable=True)
    op.alter_column('listings', 'description_quality_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0-100 quality score',
               existing_nullable=True)
    op.alter_column('listings', 'enriched_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='AI-enriched description',
               existing_nullable=True)
    op.alter_column('listings', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Cleaned description',
               existing_nullable=True)
    op.alter_column('listings', 'raw_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Original unmodified description',
               existing_nullable=True)
    op.alter_column('listings', 'energy_certificate',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='A+, A, B, B-, C, D, E, F',
               existing_nullable=True)
    op.alter_column('listings', 'price_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Price in numeric form',
               existing_nullable=True)
    op.alter_column('listings', 'typology',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='T0, T1, T2, T3, etc.',
               existing_nullable=True)
    op.alter_column('listings', 'property_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='apartment, house, land, etc.',
               existing_nullable=True)
    op.alter_column('listings', 'listing_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='sale, rent',
               existing_nullable=True)
    op.alter_column('listings', 'source_url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True,
               comment=None,
               existing_comment='Original listing URL (deduplication)')
    op.alter_column('listings', 'source_partner',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pearls',
               existing_nullable=False)
    op.alter_column('listings', 'partner_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID on the original site (e.g. REF-12345)',
               existing_nullable=True)
    op.alter_column('listings', 'scrape_job_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='Foreign key to scrape_jobs')
    op.alter_column('field_mappings', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Higher priority mappings override lower ones',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('field_mappings', 'site_key',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Optional site key for site-specific mappings (NULL = global)',
               existing_nullable=True)
    op.alter_column('field_mappings', 'language',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment="Language code: 'pt', 'en', 'es', etc.",
               existing_nullable=False,
               existing_server_default=sa.text("'pt'::character varying"))
    op.alter_column('field_mappings', 'mapping_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Type: 'field' (data field) or 'feature' (boolean amenity)",
               existing_nullable=False,
               existing_server_default=sa.text("'field'::character varying"))
    op.alter_column('field_mappings', 'target_field',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Canonical field name (e.g., 'price', 'bedrooms', 'has_garage')",
               existing_nullable=False)
    op.alter_column('field_mappings', 'source_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Raw field name from HTML (e.g., 'preço', 'price', 'quartos')",
               existing_nullable=False)
    op.alter_column('character_mappings', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Category: 'mojibake', 'currency', 'symbol'",
               existing_nullable=False,
               existing_server_default=sa.text("'mojibake'::character varying"))
    op.alter_column('character_mappings', 'target_chars',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Replacement characters',
               existing_nullable=False)
    op.alter_column('character_mappings', 'source_chars',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Source characters to replace',
               existing_nullable=False)
    op.create_table('enrichment_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('location_keywords', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('rooms_keywords', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('condition_keywords', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('amenity_keywords', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('area_keywords', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('marketing_phrases', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('scoring_weights', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('grade_thresholds', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('penalties', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('min_length_short', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('min_length_good', sa.INTEGER(), server_default=sa.text('300'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('enrichment_configs_pkey'))
    )
    op.create_index(op.f('ix_enrichment_configs_key'), 'enrichment_configs', ['key'], unique=True)
    # ### end Alembic commands ###
