"""change_scrape_jobs_json_to_jsonb

Revision ID: 88215bd33e3a
Revises: f4cab559a0b1
Create Date: 2026-06-30 13:59:27.629066
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88215bd33e3a'
down_revision: Union[str, None] = 'f4cab559a0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrape_jobs', 'progress',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='{"pages_visited": 0, "listings_found": 0, "listings_scraped": 0, "errors": 0}',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Runtime config: min_delay, max_delay, user_agent, etc.',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'logs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='{"errors": [], "warnings": [], "info": []}',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'urls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='{"found": [], "scraped": [], "failed": []}',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrape_jobs', 'urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='{"found": [], "scraped": [], "failed": []}',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'logs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='{"errors": [], "warnings": [], "info": []}',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Runtime config: min_delay, max_delay, user_agent, etc.',
               existing_nullable=True)
    op.alter_column('scrape_jobs', 'progress',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='{"pages_visited": 0, "listings_found": 0, "listings_scraped": 0, "errors": 0}',
               existing_nullable=True)
    # ### end Alembic commands ###
