"""increase energy certificate length

Revision ID: b613f8316be4
Revises: 5bc0b4733832
Create Date: 2026-07-09 11:28:54.985199
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b613f8316be4'
down_revision: Union[str, None] = '5bc0b4733832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'energy_certificate',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_comment='A+, A, B, B-, C, D, E, F, Isento',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'energy_certificate',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_comment='A+, A, B, B-, C, D, E, F, Isento',
               existing_nullable=True)
    # ### end Alembic commands ###
